-- MySQL Script generated by MySQL Workbench
-- Wed May 17 14:25:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema analyzer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema analyzer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analyzer` DEFAULT CHARACTER SET utf8 ;
USE `analyzer` ;

-- -----------------------------------------------------
-- Table `analyzer`.`scrap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyzer`.`scrap` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(256) NOT NULL,
  `http_status` INT(4) NOT NULL,
  `con_length` INT(6) NULL,
  `con_type` VARCHAR(48) NULL,
  `server` VARCHAR(48) NULL,
  `title` VARCHAR(128) NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyzer`.`headers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyzer`.`headers` (
  `id_scrap` INT UNSIGNED NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `value` INT(2) NOT NULL,
  `order` INT(4) NOT NULL,
  INDEX `headers_scrap_idx` (`id_scrap` ASC),
  CONSTRAINT `headers_scrap`
    FOREIGN KEY (`id_scrap`)
    REFERENCES `analyzer`.`scrap` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
